package views;

import java.awt.Dimension;
import controllers.classController;
import controllers.studentController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import models.Student;

public class editFrame extends javax.swing.JFrame {

    classController classCTL = new classController();
    studentController stuCTL = new studentController();
    Student studentM = new Student();

    public editFrame() {
        setTitle("Quản lí sinh viên ký túc xá - Sửa thông tin sinh viên");
        initComponents();
        inforBonus();
        setMinimumSize(new Dimension(600, 580));
        // Can giua cua so chuong trinh
        setLocationRelativeTo(null);
    }

    public editFrame(int ID) {
        studentM = stuCTL.getStudentByID(ID);
        initComponents();
        inforBonus();
    }

    //Ham khoi tao bo sung
    public void inforBonus() {
        messageDLable.setText("");
        classCTL.setModelCBB(editClassComboBox);

        idDField.setText(String.valueOf(studentM.getStID()));
        msvDField.setText(studentM.getStMSV());
        NameDField.setText(studentM.getStName());
        birthDField.setText(studentM.getStBirth());
        genderField.setText(studentM.getStGender());
        phoneDField.setText(String.valueOf(studentM.getStPhone()));
        classDField.setText(studentM.getStClass());
        placeDField.setText(studentM.getStPlace());
        roomDField.setText(String.valueOf(studentM.getStRoom()));
    }

    //Khoi phuc trang thai thuoc tinh    
    public void beginStatus() {

    }

    //Ham bat che do edit
    public void setEditOption() {
        if (editDLabel.isSelected()) {
            msvDField.setEditable(true);
            NameDField.setEditable(true);
            birthDField.setEditable(true);
            editGenderComboBox.setEnabled(true);
            phoneDField.setEditable(true);
            editClassComboBox.setEnabled(true);
            placeDField.setEditable(true);
            roomDField.setEditable(true);
            saveBTN.setEnabled(true);
        } else {
            msvDField.setEditable(false);
            NameDField.setEditable(false);
            birthDField.setEditable(false);
            editGenderComboBox.setEnabled(false);
            phoneDField.setEditable(false);
            editClassComboBox.setEnabled(false);
            placeDField.setEditable(false);
            roomDField.setEditable(false);
            saveBTN.setEnabled(false);
        }
    }

    public void setStRoom(int stRoom) {
        roomDField.setText(String.valueOf(stRoom));
    }

    //Ham xoa sinh vien
    public void deleteFunc() {
        stuCTL.deleteSt(studentM);
        JOptionPane.showMessageDialog(this, "Xóa sinh viên thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }

    //Cap nhap du lieu cho studentM
    public void updateStM() {
        studentM.setStMSV(msvDField.getText());
        studentM.setStName(NameDField.getText());
        studentM.setStGender((String) editGenderComboBox.getSelectedItem());
        studentM.setStPhone(phoneDField.getText());
        studentM.setStClass((String) editClassComboBox.getSelectedItem());
        studentM.setStPlace(placeDField.getText());
        studentM.setStRoom(Integer.parseInt(roomDField.getText())); // Sử dụng setStRoom() thay vì setStPlace()
    }

    //Ham hiển thị danh sach phòng
    public void listRoomFunc() {
        try {
            listRoomFrame listRoomFrame = new listRoomFrame();
            listRoomFrame.setParentFrame1(this); // Thiết lập parentFrame của listRoomFrame là addFrame
            listRoomFrame.setVisible(true);
            // Truyền giá trị số phòng và input
            listRoomFrame.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    String selectedRoom = listRoomFrame.getSelectedRoom(); // Lấy số phòng đã chọn
                    if (selectedRoom != null) {
                        try {
                            int stRoom = Integer.parseInt(selectedRoom);
                            setStRoom(stRoom); // Cập nhật số phòng
                        } catch (NumberFormatException ex) {
                            ex.printStackTrace();
                        }
                    }
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //Ham lưu lại
    public void saveFunc() {
        updateStM();
        stuCTL.updateStInfor(studentM);
        JOptionPane.showMessageDialog(this, "Đã sửa thông tin sinh viên thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailLabel = new javax.swing.JLabel();
        NameDField = new javax.swing.JTextField();
        birthDField = new javax.swing.JTextField();
        roomDField = new javax.swing.JTextField();
        editGenderComboBox = new javax.swing.JComboBox<>();
        idDField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saveBTN = new javax.swing.JButton();
        delBTN = new javax.swing.JButton();
        messageDLable = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        editClassComboBox = new javax.swing.JComboBox<>();
        editDLabel = new javax.swing.JCheckBox();
        classDField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        phoneDField = new javax.swing.JTextField();
        placeDField = new javax.swing.JTextField();
        msvDField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        detailLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        detailLabel.setForeground(new java.awt.Color(0, 51, 51));
        detailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailLabel.setText("THÔNG TIN SINH VIÊN");

        NameDField.setEditable(false);
        NameDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameDFieldActionPerformed(evt);
            }
        });

        birthDField.setEditable(false);
        birthDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthDFieldActionPerformed(evt);
            }
        });

        roomDField.setEditable(false);
        roomDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomDFieldActionPerformed(evt);
            }
        });

        editGenderComboBox.setEditable(true);
        editGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        editGenderComboBox.setEnabled(false);
        editGenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGenderComboBoxActionPerformed(evt);
            }
        });

        idDField.setEditable(false);
        idDField.setEnabled(false);
        idDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("Họ tên");

        jLabel4.setText("Ngày sinh");

        jLabel5.setText("Giới tính");

        jLabel6.setText("Số điện thoại");

        saveBTN.setBackground(new java.awt.Color(0, 102, 204));
        saveBTN.setForeground(new java.awt.Color(255, 255, 255));
        saveBTN.setText("LƯU");
        saveBTN.setEnabled(false);
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        delBTN.setBackground(new java.awt.Color(204, 0, 0));
        delBTN.setForeground(new java.awt.Color(255, 255, 255));
        delBTN.setText("XÓA");
        delBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBTNActionPerformed(evt);
            }
        });

        messageDLable.setForeground(new java.awt.Color(204, 0, 0));
        messageDLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageDLable.setText("Thông báo");

        jLabel10.setText("Lớp");

        editClassComboBox.setEditable(true);
        editClassComboBox.setEnabled(false);

        editDLabel.setText("Sửa");
        editDLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDLabelActionPerformed(evt);
            }
        });

        classDField.setEditable(false);

        genderField.setEditable(false);
        genderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Mã sinh viên");

        jLabel9.setText("Số phòng");

        jLabel7.setText("Địa chỉ");

        phoneDField.setEditable(false);
        phoneDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneDFieldActionPerformed(evt);
            }
        });

        placeDField.setEditable(false);
        placeDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeDFieldActionPerformed(evt);
            }
        });

        msvDField.setEditable(false);
        msvDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msvDFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Lựa chọn phòng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1listRoomBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idDField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editDLabel))
                    .addComponent(placeDField)
                    .addComponent(phoneDField)
                    .addComponent(NameDField)
                    .addComponent(birthDField)
                    .addComponent(msvDField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(classDField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(roomDField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(delBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(messageDLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(detailLabel)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(editDLabel))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(msvDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneDField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(editClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(placeDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(roomDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageDLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBTN)
                    .addComponent(delBTN))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editDLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDLabelActionPerformed
        // TODO add your handling code here:
        setEditOption();
    }//GEN-LAST:event_editDLabelActionPerformed

    private void delBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBTNActionPerformed
        // TODO add your handling code here:
        deleteFunc();
    }//GEN-LAST:event_delBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        saveFunc();
    }//GEN-LAST:event_saveBTNActionPerformed

    private void genderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFieldActionPerformed

    private void editGenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGenderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editGenderComboBoxActionPerformed

    private void placeDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeDFieldActionPerformed

    private void phoneDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneDFieldActionPerformed

    private void birthDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthDFieldActionPerformed

    private void NameDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameDFieldActionPerformed

    private void msvDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msvDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msvDFieldActionPerformed

    private void idDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idDFieldActionPerformed

    private void roomDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomDFieldActionPerformed

    private void jButton1listRoomBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1listRoomBTNActionPerformed
        // TODO add your handling code here:
        listRoomFunc();
    }//GEN-LAST:event_jButton1listRoomBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameDField;
    private javax.swing.JTextField birthDField;
    private javax.swing.JTextField classDField;
    private javax.swing.JButton delBTN;
    private javax.swing.JLabel detailLabel;
    private javax.swing.JComboBox<String> editClassComboBox;
    private javax.swing.JCheckBox editDLabel;
    private javax.swing.JComboBox<String> editGenderComboBox;
    private javax.swing.JTextField genderField;
    private javax.swing.JTextField idDField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel messageDLable;
    private javax.swing.JTextField msvDField;
    private javax.swing.JTextField phoneDField;
    private javax.swing.JTextField placeDField;
    private javax.swing.JTextField roomDField;
    private javax.swing.JButton saveBTN;
    // End of variables declaration//GEN-END:variables

}
