package views;

import controllers.classController;
import controllers.studentController;
import controllers.RoomController;
import javax.swing.table.DefaultTableModel;
import models.Student;
import models.User;
import quanlyktx.data.excelFile;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import util.ColorFrame;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.Timer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import java.awt.Dimension;

public class listRoomFrame extends javax.swing.JFrame {

    RoomController rmCTL = new RoomController();
    private addFrame parentFrame;
    private editFrame parentFrame1;
    private String selectedRoom;

    public listRoomFrame() {
        initComponents();
        setDetail();
    }

//Ham Them cau hinh cho LístRoom
    public void setDetail() {
        setTitle("Quản lí sinh viên ký túc xá - Danh sách phòng");
        loadTable(true);

        setMinimumSize(new Dimension(700, 450));
        // Can giua cua so chuong trinh
        setLocationRelativeTo(null);

    }

// Phương thức trả về số phòng đã chọn
    public String getSelectedRoom() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            return jTable1.getValueAt(selectedRow, 0).toString();
        }
        return null;
    }

    public void setParentFrame(addFrame parentFrame) {
        this.parentFrame = parentFrame;
    }

    public void setParentFrame1(editFrame parentFrame) {
        this.parentFrame1 = parentFrame;
    }

//Ham update
    public void UpdateInfor() {
        setNumberOfSt();
    }

//Ham double cho add
    public void addDoubleClickEvent() {
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int selectedRow = jTable1.getSelectedRow();
                    if (selectedRow >= 0) {
                        String roomIdString = jTable1.getValueAt(selectedRow, 0).toString(); // Lấy ID của phòng từ cột "ID"
                        try {
                            int roomId = Integer.parseInt(roomIdString);
                            if (parentFrame != null) {
                                parentFrame.setStRoom(roomId); // Gửi ID của phòng đến addFrame
                                dispose();
                            }
                        } catch (NumberFormatException ex) {
                            ex.printStackTrace();
                        }
                    }
                }
            }
        });
    }

//Ham double cho edit
public void addDoubleClickEvent(final boolean forEdit) {
    jTable1.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2) {
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow >= 0) {
                    String roomIdString = jTable1.getValueAt(selectedRow, 0).toString(); 
                    try {
                        int roomId = Integer.parseInt(roomIdString);
                        if (forEdit) {
                            if (parentFrame1 != null) {
                                parentFrame1.setStRoom(roomId);
                                dispose(); // Đóng frame sau khi lựa chọn
                            }
                        } else {
                            if (parentFrame != null) {
                                parentFrame.setStRoom(roomId);
                                dispose(); // Đóng frame sau khi lựa chọn
                            }
                        }
                    } catch (NumberFormatException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        }
    });
}

    public void setNumberOfSt() {
        int count = jTable1.getRowCount();
        numberLabel6.setText("Số lượng: " + count);
    }

    //Ham load csdl hiển thi ra table
    public void loadTable(boolean all) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        rmCTL.loadDBRoom(jTable1, all);
        UpdateInfor();

        addDoubleClickEvent();
        addDoubleClickEvent(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        detailLabel1 = new javax.swing.JLabel();
        numberLabel6 = new javax.swing.JLabel();
        classSelectBox3 = new javax.swing.JComboBox<>();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Số Phòng", "Tầng", "Loại Phòng", "Số Lượng", "Tòa", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        detailLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        detailLabel1.setForeground(new java.awt.Color(0, 51, 51));
        detailLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailLabel1.setText("DANH SÁCH PHÒNG");

        numberLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numberLabel6.setForeground(new java.awt.Color(0, 51, 51));
        numberLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberLabel6.setText("Số lượng: 0");

        classSelectBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        classSelectBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classSelectBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(detailLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addComponent(numberLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classSelectBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(detailLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classSelectBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classSelectBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classSelectBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classSelectBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listRoomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listRoomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listRoomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listRoomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listRoomFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> classSelectBox3;
    private javax.swing.JLabel detailLabel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel numberLabel6;
    // End of variables declaration//GEN-END:variables
}
