/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Dimension;

/**
 *
 * @author toan4
 */
public class NoiQuy extends javax.swing.JFrame {

    /**
     * Creates new form NoiQuy
     */
    public NoiQuy() {
        initComponents();
        setDetail();
    }
    
    public void setDetail(){
        setTitle("Nội quy");
        setMinimumSize(new Dimension(1000, 400));
        // Can giua cua so chuong trinh
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Điều 1. Người không có nhiệm vụ không được vào ký túc xá sinh viên.\n\nĐiều 2. Khách đến liên hệ công tác hoặc thăm người nhà ở ký túc xá \nphải xuất trình giấy tờ với nhân viên trực bảo vệ ký túc xá.\n\nĐiều 3. Người ở ký túc xá khi ra vào ký túc xá phải xuất trình thẻ sinh viên \nvới nhân viên trực bảo vệ ký túc xá. Từ 23h ngày hôm trước đến 5h ngày hôm sau, \nnghiêm cấm người ở ký túc xá ra vào ký túc xá (trừ trường hợp có lý do chính đáng).\n\nĐiều 4. Người ở ký túc xá phải thực hiện đúng các cam kết đã ký với người quản lý.\n\nĐiều 5. Không cho người ngoài vào phòng ở và không tiếp khách quá 23h đêm.\n\nĐiều 6. Không đưa xe đạp, xe máy vào ký túc xá và phải để đúng nơi quy định.\n\nĐiều 7. Không đun nấu, tổ chức ăn, uống rượu, bia, xả rác bừa bãi trong ký túc xá.\n\nĐiều 8. Không gây tiếng ồn, đốt các chất liệu gây khói, lửa, nổ.\n\nĐiều 9. Không sử dụng tàng trữ các loại vũ khí, hung khí dao, giáo, mác, côn… chất nổ, \nchất gây cháy, chất độc hại, chất gây nghiện, tiêm chích ma túy.\n\nĐiều 10. Giữ gìn phòng ở gọn gàng, sạch đẹp, văn minh, lịch sự, tích cực tham gia \ncác phòng trào hội thi do Ban quản lý ký túc xá phát động và tổ chức.\n");
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField1.setText("                             NỘI QUY KÍ TÚC XÁ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoiQuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoiQuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoiQuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoiQuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoiQuy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
